name: Workflow
on:
  push:
    branches:
      - rama_02

jobs:
  SAST:
    runs-on: ubuntu-24.05
    steps: 
        - name: Checkout code
          uses: action/checkout@v3

        - name: Set up JDK
          uses: action/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Set enviroment variables
          run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
