name: Workflow
on:
  push:
    branches:
      - rama_02

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps: 
        - name: Checkout code
          uses: action/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Set enviroment variables
          run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

        - name: Validate and configure build.gradle
          env:
            TOKEN_EF: ${{ secrets.TOKEN_EF }}
          run: |
            if [ -f "build.gradle" ]; then
              echo "Encontró el archivo"
              echo "Verificando cpnfiguración del plugin sonar"
              if ! grep -q 'id "org.sonarqube" version "3.3"' build.gradle; then
                sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
                echo "Plugin de Sonarcloud añadido a build.gradle"

            else
              echo "Plugin de Sonarcloud ya esta configurado en build.gradle"
            fi


            else
              echo "No se encuentra el archivo build.gradle"
              exit 1
             
            fi
