name: Workflow
on:
  push:
    branches:
      - rama_02

jobs:
  SAST:
    runs-on: ubuntu-24.04
    steps: 
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Set enviroment variables
          run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

        - name: Validate and configure build.gradle
          env:
            TOKEN_EF: ${{ secrets.TOKEN_EF }}
          run: |
            if [ -f "build.gradle" ]; then
              echo "Encontró el archivo"
              echo "Verificando cpnfiguración del plugin sonar"
              if ! grep -q 'id "org.sonarqube" version "3.3"' build.gradle; then
                sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
                echo "Plugin de Sonarcloud añadido a build.gradle"
              else
                echo "Plugin de Sonarcloud ya esta configurado en build.gradle"
              fi
            else
              echo "No se encuentra el archivo build.gradle"
              exit 1
            fi

        - name: Validate and create Sonarcloud project
          id: validate-project
          env: 
            TOKEN_EF: ${{ secrets.TOKEN_EF }}
            REPO_NAME: ${{ github.event.repository.name }}
          run: |
            echo "Verificando si el proyecto $REPO_NAME existe en Sonarcloud"
            response=$(curl -s -o /dev/null -w "%{http_code}" -u "$TOKEN_EF:" \
              "https://sonarcloud.io/api/projects/search?projects=$REPO_NAME")

            if [ "$response" -ne 200 ]; then
              echo "El proyecto no existe en SonarCloud"
              create_response=$(curl -s -w "%{http_code}" -o /dev/null -X POST -u "$TOKEN_EF:" \
                "https://sonarcloud.io/api/projects/create" \
                -d "name=$REPO_NAME" \
                -d "project=$REPO_NAME" \
                -d "organization=catalabs" \
                -d "project=public")

              if [ "$response" -ne 201 ]; then
                echo "Proyecto creado exitosamente"
              fi

              echo "Estableciendo rama main por defecto"
              curl -s -f -X POST -u "$TOKEN_EF:" \
                "https://sonarcloud.io/api/project_branches/rename" \
                -d "name=main"
                -d "project=$REPO_NAME"
              echo "project_created=true" >> $GITHUB_ENV
            else
              echo "El proyecto ya existe en SonarCloud"
              echo "project_created=false" >> $GITHUB_ENV
            fi

            
         